const SERVICE_COPY = {
  zh: {
    heroEyebrow: 'TK168 MOTOR GALLERY',
    heroTitle: '增值服务',
    heroSubtitle: '围绕二手车交易、交付与持有阶段，提供更省心的线下协同支持。',
    overviewKicker: 'VALUE-ADDED SERVICES',
    overviewTitle: '坚持以客户需求为中心，通过标准化服务流程与专业团队协作，为客户提供贯穿购车全流程的服务支持。',
    overviewSubtitle: '从车辆咨询到交付完成，再到后续服务支持，我们以统一的服务流程，保障每一个环节的专业性和效率',
    overviewText1: '',
    overviewText2: 'TK168 以客户需求为中心，整合购前咨询、交付协调及售后支持等服务内容，根据车辆情况与实际需求提供专业建议，协助客户高效完成各项流程，实现更加顺畅的交付体验',
    overviewText3: '我们坚持以规范的服务标准和高效的协同机制，持续提升服务品质，为每一位客户提供专业、可靠且值得信赖的全流程服务。',
    overviewPrimary: '预约咨询',
    overviewSecondary: '查看企业简介',
    metric1Label: '服务响应',
    metric1Value: '1-2 工作日',
    metric2Label: '服务语言',
    metric2Value: '中 / 日 / 英',
    metric3Label: '服务模式',
    metric3Value: '专属顾问全程服务',
    metric4Label: '服务范围',
    metric4Value: '购前咨询｜车辆交付｜售后支持',
    metric5Label: 'TK168 Service',
    metric5Value: '让每一次购车，都更加安心。',
    metric5Desc: '规范的流程、透明的信息与持续的服务支持，让客户能够更专注于车辆本身，而无需为繁琐流程担忧。',
    metricTag1: '购车评估',
    metricTag2: '手续协同',
    metricTag3: '整备维护',
    flowKicker: 'SERVICE PROCESS',
    flowTitle: '全流程服务，为每一次交付保驾护航',
    flowSubtitle: '围绕客户需求，整合购前咨询、手续办理、车辆整备及售后支持等服务，打造更加高效、透明的服务体验。',
    flowStep1Label: '01',
    flowStep1Title: '预约咨询',
    flowStep1Text: '根据车辆情况及客户需求，确认服务项目、预约时间，并做好维修前准备。',
    flowStep2Label: '02',
    flowStep2Title: '检测与方案确认',
    flowStep2Text: '对车辆进行专业检测，说明检查结果、维修建议及预计费用，经客户确认后开始施工。',
    flowStep3Label: '03',
    flowStep3Title: '维修与质量把控',
    flowStep3Text: '严格按照维修标准开展施工，关键节点全程把控，确保维修质量与交付品质。',
    flowStep4Label: '04',
    flowStep4Title: '交付与售后支持',
    flowStep4Text: '交付时说明维修内容及注意事项，并提供后续保养建议与持续售后支持。',
    matrixKicker: 'SERVICE OFFERINGS',
    matrixTitle: '覆盖购前、交付与售后的专业服务',
    matrixSubtitle: '围绕车辆全生命周期，提供覆盖购前咨询、车辆交付及售后支持的一站式服务，满足客户在不同阶段的实际需求。',
    module1Title: '购前评估',
    module1Text: '结合车辆状况、维修记录及使用需求，提供专业评估建议，帮助客户全面了解车辆信息，为购车决策提供参考。',
    module2Title: '保险咨询',
    module2Text: '根据车辆类型及使用场景，提供保险方案说明与投保建议，了解客户完成相关办理流程。',
    module3Title: '手续办理',
    module3Text: '协助办理车辆交付所需的相关资料及手续，统筹各项办理流程，提升交付效率。',
    module4Title: '交付检查',
    module4Text: '车辆交付前进行重点项目检查与确认，确保车辆状态及交付内容清晰透明。',
    module5Title: '维修整备',
    module5Text: '根据车辆实际情况开展交付前整备，并提供后续维修与技术支持服务。',
    module6Title: '售后支持',
    module6Text: '持续提供年检、续保及车辆维护等服务，为客户打造更加安心的用车体验。',
    sceneKicker: 'COMMON COMBINATIONS',
    sceneTitle: '咨询与支持',
    sceneSubtitle: '无论您正处于购车咨询、车辆交付还是售后服务阶段， 我们都希望通过清晰的服务说明和常见问题解答， 帮助您更高效地了解服务流程，获得专业支持。',
    scene1Title: '购车咨询',
    scene1Text: '正在比较车型或了解购车方案。',
    scene2Title: '车辆交付',
    scene2Text: '已确认购车，准备办理交付手续。',
    scene3Title: '售后支持',
    scene3Text: '车辆交付完成，持续提供后续服务。',
    faqKicker: 'SERVICE FAQ',
    faqTitle: '常见问题',
    faqSubtitle: '针对客户在咨询、购车及售后过程中常见的问题进行解答，帮助您更快速地了解我们的服务。',
    faq1Question: '提交咨询后，多久会有工作人员联系？',
    faq1Answer: '我们将在收到咨询后尽快安排专属顾问与您联系。一般情况下，将于 1–2 个工作日内 完成初步对接，并根据您的需求提供相应建议。',
    faq2Question: '尚未确定购买车辆，可以提前咨询吗？',
    faq2Answer: '当然可以。无论您仍在比较车型，还是希望了解预算、保险或购车流程，我们都欢迎您提前咨询，由专业顾问为您提供建议。',
    faq3Question: '车辆交付后，还能继续获得售后服务吗？',
    faq3Answer: '可以。车辆交付完成后，我们仍可提供维修保养、年检、续保及其他用车支持，陪伴您安心用车。'
  },
  ja: {
    heroEyebrow: 'TK168 MOTOR GALLERY',
    heroTitle: '付加サービス',
    heroSubtitle: '中古車の取引、納車、保有フェーズに合わせて、店頭での実務支援を一つの導線にまとめています。',
    overviewKicker: 'VALUE-ADDED SERVICES',
    overviewTitle: 'お客様のニーズを第一に考え、標準化されたサービスフローと専門スタッフによる対応により、ご購入前のご相談からご納車、アフターサポートまで、一貫したサービス体制を構築しています。',
    overviewSubtitle: '各工程を統一したサービス基準のもとで進めることで、品質と効率の両立を図り、安心してご利用いただけるサービスをご提供します。',
    overviewText1: '',
    overviewText2: 'お客様のニーズを第一に考え、標準化されたサービスフローと専門スタッフによる対応により、ご購入前のご相談からご納車、アフターサポートまで、一貫したサービス体制を構築しています。',
    overviewText3: '統一されたサービス基準と円滑な連携体制のもと、サービス品質の向上に継続して取り組み、お客様に信頼いただけるサービスをご提供します。',
    overviewPrimary: '相談を予約する',
    overviewSecondary: '企業紹介を見る',
    metric1Label: 'お問い合わせ対応',
    metric1Value: '1-2 営業日',
    metric2Label: '対応言語',
    metric2Value: '中 / 日 / 英',
    metric3Label: 'サービス体制',
    metric3Value: '専任スタッフによる一貫サポート',
    metric4Label: 'サービス内容',
    metric4Value: 'ご購入前のご相談｜ご納車｜アフターサポート',
    metric5Label: 'TK168 Service',
    metric5Value: '安心のカーライフを、一台一台に。',
    metric5Desc: '標準化されたサービスフローと継続的なサポートにより、ご購入前からご納車後まで安心してご利用いただけるサービスをご提供します。',
    metricTag1: '査定',
    metricTag2: '手続き',
    metricTag3: '整備',
    flowKicker: 'SERVICE PROCESS',
    flowTitle: 'ご購入前からご納車後まで、安心を支えるサービス。',
    flowSubtitle: 'お客様のニーズに寄り添い、ご購入前のご相談から各種お手続き、車両整備、アフターサポートまで、一貫したサービスをご提供します。安心・透明性・効率を重視し、快適なお取引をサポートします。',
    flowStep1Label: '01',
    flowStep1Title: 'ご相談・ご予約',
    flowStep1Text: 'ご希望の車種やご予算、ご利用目的をお伺いし、ご来店予約やご購入に関するご相談を承ります。',
    flowStep2Label: '02',
    flowStep2Title: '車両確認・お見積り',
    flowStep2Text: '車両の状態や装備内容をご説明し、お見積りや各種条件をご案内します。内容をご確認いただいたうえで、ご契約手続きを進めます。',
    flowStep3Label: '03',
    flowStep3Title: 'ご納車・アフターサポート',
    flowStep3Text: 'ご納車後も、車検・メンテナンス・保険など、継続的なサポートをご提供します。',
    flowStep4Label: '04',
    flowStep4Title: 'ご納車・アフターサポート',
    flowStep4Text: 'ご納車時には車両の状態や装備内容、お取り扱い方法などをご説明します。ご納車後も車検・メンテナンス・保険など、継続的なアフターサポートをご提供し、安心してカーライフをお楽しみいただけるようサポートいたします。',
    matrixKicker: 'SERVICE OFFERINGS',
    matrixTitle: 'ご購入前からご納車後まで、一貫したサービス。',
    matrixSubtitle: 'ご購入前のご相談、ご納車、アフターサポートまで、お客様に寄り添ったワンストップサービスをご提供します。専門スタッフが各ステージに応じたサポートを行い、安心してカーライフをお楽しみいただける環境を整えています。',
    module1Title: '車両評価',
    module1Text: '車両の状態や整備履歴、ご利用目的などを総合的に確認し、専門スタッフがお客様に最適な車両選びをご提案します。安心してご購入をご検討いただけるよう、わかりやすくご案内いたします。',
    module2Title: '保険相談',
    module2Text: '車両の種類やご利用状況に合わせた保険プランをご案内し、最適な補償内容をご提案します。ご契約に関する各種手続きもサポートいたします。',
    module3Title: '各種お手続き',
    module3Text: 'ご納車に必要な書類や各種手続きをサポートし、スムーズなご納車に向けて一貫して対応いたします。',
    module4Title: '納車前点検',
    module4Text: 'ご納車前に車両の状態や主要項目を点検・確認し、安心してお乗りいただける状態でご納車いたします。',
    module5Title: '納車前整備',
    module5Text: '車両の状態に応じて必要な整備を実施し、品質基準に基づいた点検・整備を行います。ご納車後のメンテナンスや技術サポートにも対応しています。',
    module6Title: 'アフターサポート',
    module6Text: 'ご納車後も車検・メンテナンス・保険更新など、継続的なサポートをご提供し、安心・快適なカーライフをサポートいたします。',
    sceneKicker: 'COMMON COMBINATIONS',
    sceneTitle: 'サポート・ご案内',
    sceneSubtitle: 'ご購入をご検討中のお客様から、ご納車後のアフターサポートをご利用のお客様まで、各サービスの内容やよくあるご質問をご案内しています。サービスの流れをわかりやすくご紹介し、安心してご利用いただけるようサポートいたします。',
    scene1Title: 'ご購入相談',
    scene1Text: '車種の比較やご購入プランについてご検討中のお客様向けに、専門スタッフがご相談を承ります。',
    scene2Title: 'ご納車',
    scene2Text: 'ご契約後の各種お手続きからご納車まで、スムーズに進められるようサポートいたします。',
    scene3Title: 'アフターサポート',
    scene3Text: 'ご納車後も、車検・メンテナンス・保険など、継続的なサポートをご提供いたします。',
    faqKicker: 'SERVICE FAQ',
    faqTitle: 'よくあるご質問',
    faqSubtitle: 'ご購入前のご相談からご納車後のアフターサポートまで、お客様からよくいただくご質問をまとめています。サービス内容やお手続きについて、安心してご利用いただけるようわかりやすくご案内します。',
    faq1Question: 'お問い合わせ後、どのくらいで連絡がありますか。',
    faq1Answer: 'お問い合わせ内容を確認後、担当スタッフより順次ご連絡いたします。通常は1〜2営業日以内を目安に初回のご案内を行い、お客様のご要望に合わせたご提案をいたします。',
    faq2Question: '購入する車両が決まっていなくても相談できますか。',
    faq2Answer: 'もちろんです。車種の比較やご予算、ご購入プラン、保険、各種お手続きなど、どのような内容でもお気軽にご相談ください。専門スタッフがお客様に最適なご提案をいたします。',
    faq3Question: '納車後もサポートを受けられますか。',
    faq3Answer: 'はい。ご納車後も車検・メンテナンス・保険更新など、継続的なアフターサポートをご提供しています。安心してカーライフをお楽しみいただけるよう、長期的にサポートいたします。'
  },
  en: {
    heroEyebrow: 'TK168 MOTOR GALLERY',
    heroTitle: 'Value-added Services',
    heroSubtitle: 'Practical offline support around used-car transactions, delivery, and ownership.',
    overviewKicker: 'VALUE-ADDED SERVICES',
    overviewTitle: 'Keeping pre-purchase judgment, delivery coordination, and aftercare on one service line',
    overviewSubtitle: 'In real used-car business, customers care less about abstract service names and more about who follows up, when they hear back, and what can be handled together.',
    overviewText1: 'After choosing a car, the time-consuming parts are often valuation, document checks, insurance discussions, pre-delivery inspection, and maintenance planning.',
    overviewText2: 'TK168 is best used as one window that organizes those scattered tasks and helps decide what should be handled first based on the vehicle and the customer’s use case.',
    overviewText3: 'So the page is not trying to say “we do everything”, but rather “these are the areas where we can reduce detours”.',
    overviewPrimary: 'Book a consultation',
    overviewSecondary: 'View company profile',
    metric1Label: 'First reply',
    metric1Value: '1-2 business days',
    metric2Label: 'Languages',
    metric2Value: 'CN / JP / EN',
    metric3Label: 'Service Model',
    metric3Value: 'Dedicated Support Throughout Your Journey',
    metric4Label: 'Service Coverage',
    metric4Value: 'Pre-Purchase Consultation | Vehicle Delivery | After-Sales Support',
    metric5Label: 'TK168 Service',
    metric5Value: 'Confidence in Every Purchase.',
    metric5Desc: 'Standardized service processes, transparent communication, and continuous support allow you to focus on choosing the right vehicle while we take care of every step of the process.',
    metricTag1: 'Appraisal',
    metricTag2: 'Paperwork',
    metricTag3: 'Maintenance',
    flowKicker: 'SERVICE PROCESS',
    flowTitle: 'End-to-End Service, Every Step with Confidence.',
    flowSubtitle: 'Centered around our customers\' needs, we integrate pre-purchase consultation, documentation assistance, vehicle preparation, and after-sales support into one seamless service experience, delivering a process that is efficient, transparent, and reliable.',
    flowStep1Label: '01',
    flowStep1Title: 'Consultation & Reservation',
    flowStep1Text: 'We discuss your vehicle needs, confirm the service details and appointment schedule, and provide personalized support to ensure a smooth and efficient purchasing experience.',
    flowStep2Label: '02',
    flowStep2Title: 'Inspection & Confirmation',
    flowStep2Text: 'We inspect the vehicle, explain its condition and preparation details, and confirm the delivery process to ensure everything is ready before handover.',
    flowStep3Label: '03',
    flowStep3Title: 'Maintenance & Quality Assurance',
    flowStep3Text: 'Our technicians carry out all maintenance according to established quality standards, with thorough inspections throughout the process to ensure reliable workmanship and high-quality vehicle delivery.',
    flowStep4Label: '04',
    flowStep4Title: 'Delivery & After-Sales Support',
    flowStep4Text: 'During vehicle delivery, we explain the vehicle condition, completed preparation work, and important operating information. We also provide maintenance recommendations and continuous after-sales support to help you enjoy your vehicle with confidence.',
    matrixKicker: 'SERVICE OFFERINGS',
    matrixTitle: 'Comprehensive Services from Purchase to Ownership',
    matrixSubtitle: 'We provide a one-stop service covering pre-purchase consultation, vehicle delivery, and after-sales support. From selecting the right vehicle to ongoing maintenance and customer care, we are committed to delivering a seamless and reliable ownership experience at every stage.',
    module1Title: 'Vehicle Evaluation & Purchase Consultation',
    module1Text: 'We assess the vehicle\'s condition, maintenance history, and your individual requirements to provide professional recommendations, helping you make informed purchasing decisions with confidence.',
    module2Title: 'Insurance Consultation',
    module2Text: 'We explain suitable insurance options based on the vehicle type and your driving needs, providing guidance throughout the insurance application process.',
    module3Title: 'Documentation & Registration',
    module3Text: 'We assist with all documentation and procedures required for vehicle delivery, coordinating every step to ensure an efficient and seamless handover.',
    module4Title: 'Pre-Delivery Inspection',
    module4Text: 'Before delivery, we carry out a comprehensive inspection and final confirmation to ensure the vehicle\'s condition and all delivery details meet our quality standards.',
    module5Title: 'Delivery preparation and repair',
    module5Text: 'Vehicle Preparation',
    module6Title: 'After-Sales Support',
    module6Text: 'We continue to provide vehicle inspections, insurance renewal assistance, maintenance guidance, and other after-sales services to help you enjoy worry-free ownership.',
    sceneKicker: 'COMMON COMBINATIONS',
    sceneTitle: 'Support & Guidance',
    sceneSubtitle: 'Whether you\'re exploring your vehicle options, preparing for delivery, or seeking after-sales assistance, we\'re here to help. Clear service information and answers to frequently asked questions make it easy to understand each step of the process and receive professional support whenever you need it.',
    scene1Title: 'Purchase Consultation',
    scene1Text: 'Compare vehicle options, explore financing and purchase plans, and receive expert guidance to help you choose the right vehicle.',
    scene2Title: 'Vehicle Delivery',
    scene2Text: 'Your purchase has been confirmed. We\'ll guide you through the delivery process and complete all necessary procedures for a smooth handover.',
    scene3Title: 'After-Sales Support',
    scene3Text: 'After delivery, we continue to provide maintenance guidance, inspections, insurance assistance, and ongoing customer support to help you enjoy worry-free ownership.',
    faqKicker: 'SERVICE FAQ',
    faqTitle: 'Frequently Asked Questions',
    faqSubtitle: 'Find answers to the questions customers ask most often about our services, from initial consultation and vehicle purchase to delivery and after-sales support.',
    faq1Question: 'How soon will I be contacted after submitting an inquiry?',
    faq1Answer: 'Once we receive your inquiry, a dedicated advisor will contact you as soon as possible. In most cases, we\'ll respond within 1–2 business days with initial guidance and recommendations tailored to your needs.',
    faq2Question: 'Can I contact you even if I haven\'t decided which vehicle to purchase?',
    faq2Answer: 'Absolutely. Whether you\'re comparing different models or would like advice on your budget, insurance options, or the purchasing process, our team is happy to assist you. Our experienced advisors will help you find the solution that best fits your needs.',
    faq3Question: 'Will I continue to receive support after my vehicle is delivered?',
    faq3Answer: 'Yes. After delivery, we continue to provide maintenance guidance, vehicle inspections, insurance renewal assistance, and a range of after-sales services to help you enjoy worry-free vehicle ownership.'
  }
};

function applyServiceCopy(language = 'ja') {
  const catalog = SERVICE_COPY[language] || SERVICE_COPY.ja || SERVICE_COPY.zh;
  document.title = `${catalog.heroTitle} — TK168 Premium Automotive`;
  document.querySelectorAll('[data-service-key]').forEach((element) => {
    const key = element.dataset.serviceKey || '';
    if (catalog[key]) element.textContent = catalog[key];
  });
}

window.TK168CommonLinks?.applyCommonLinks();
window.TK168PageChrome?.applyPageChrome({
  pageKey: 'service',
  inventoryHref: 'brand.html',
  serviceHref: 'service.html'
});

applyServiceCopy(window.TK168I18N?.getLanguage?.() || 'ja');

window.addEventListener('tk168:languagechange', (event) => {
  applyServiceCopy(event.detail?.language || 'ja');
});
