const SERVICE_COPY = {
  zh: {
    heroEyebrow: 'TK168 MOTOR GALLERY',
    heroTitle: '增值服务',
    heroSubtitle: '围绕二手车交易、交付与持有阶段，提供更省心的线下协同支持。',
    overviewKicker: 'VALUE-ADDED SERVICES',
    overviewTitle: '把购前判断、交付协同和后续维护放在一条服务线上',
    overviewSubtitle: '真实的二手车业务里，客户最在意的不是抽象服务名，而是谁来跟进、什么时候反馈、哪些事项能一起处理。',
    overviewText1: '很多客户在定车之后，才发现真正费时间的是估价判断、资料确认、保险沟通、交付前检查和后续维护安排。',
    overviewText2: 'TK168 更适合做的是把这些零散事项合并到同一窗口，由顾问根据车辆状态和客户用途，建议先处理哪些、后处理哪些。',
    overviewText3: '这样页面呈现出来的不是“我们什么都能做”，而是“哪些事情可以替你少走弯路”。',
    overviewPrimary: '预约咨询',
    overviewSecondary: '查看企业简介',
    metric1Label: '首次反馈',
    metric1Value: '1-2 工作日',
    metric2Label: '沟通语言',
    metric2Value: '中 / 日 / 英',
    metric3Label: '服务方式',
    metric3Value: '到店预约 / 远程沟通',
    metric4Label: '主要对象',
    metric4Value: '在库成交客户与咨询客户',
    metric5Label: '实际建议',
    metric5Value: '先确认车辆与交付节点，再决定服务组合',
    metric5Desc: '这样更贴近真实成交流程，也能减少中途反复补资料或改安排。',
    metricTag1: '购车评估',
    metricTag2: '手续协同',
    metricTag3: '整备维护',
    flowKicker: 'MAINTENANCE FLOW',
    flowTitle: '车辆维修保养通常怎么推进',
    flowSubtitle: '把预约、检查、报价、施工和交付说明拆开写清楚，比泛泛地说“可以维修保养”更让客户安心。',
    flowStep1Label: '01',
    flowStep1Title: '预约与问题确认',
    flowStep1Text: '先确认异响、灯报码、保养周期或碰伤位置，方便判断是否需要安排到店检查。',
    flowStep2Label: '02',
    flowStep2Title: '到店检查与报价说明',
    flowStep2Text: '根据车辆实际状态做基础检查，再把建议处理项目、所需时间和费用区间说明清楚。',
    flowStep3Label: '03',
    flowStep3Title: '维修保养执行',
    flowStep3Text: '确认方案后安排保养、易损件更换或小范围维修，过程中由同一窗口持续跟进进度。',
    flowStep4Label: '04',
    flowStep4Title: '完工交付与后续提醒',
    flowStep4Text: '完工后说明本次处理内容、后续观察点和下次保养建议，让客户清楚车辆接下来怎么用、何时再回店。',
    matrixKicker: 'SERVICE MATRIX',
    matrixTitle: '成交前后最常被问到的六项服务',
    matrixSubtitle: '预算判断、保险说明、手续资料和交付前检查，通常会比维修保养更早进入客户的决策流程。',
    module1Title: '购前评估',
    module1Text: '结合上牌年份、里程、配置和车况，先帮客户判断这台车是否值得继续谈下去。',
    module2Title: '保险说明与协助',
    module2Text: '按车辆用途和预算做基础说明，帮助客户更快理解该准备什么、什么时候确认。',
    module3Title: '手续资料协同',
    module3Text: '把成交前后容易卡住的资料确认、时间提醒和手续对接，统一放到同一窗口处理。',
    module4Title: '交付前检查',
    module4Text: '把客户最关心的车况检查前置说明，让交车阶段更透明，也更方便做取舍判断。',
    module5Title: '交车整备与维修',
    module5Text: '适合交付前的基础整备，以及交付后出现的小问题处理与维修建议。',
    module6Title: '年检、续保与后续维护',
    module6Text: '面向持有阶段客户，继续承接年检、续保安排和后续维护提醒。',
    sceneKicker: 'COMMON COMBINATIONS',
    sceneTitle: '三种最常见的咨询场景',
    sceneSubtitle: '这部分不再讲抽象套餐，而是用真实门店里更常见的咨询方式来组织内容。',
    scene1Title: '还在比较车辆',
    scene1Text: '适合还在看车型、比预算的客户，先做购前评估，再补基本手续与保险说明。',
    scene2Title: '已经决定成交',
    scene2Text: '适合已经定车的客户，把资料、检查、保险和交车前整备一次性理顺。',
    scene3Title: '已经进入持有阶段',
    scene3Text: '适合已经提车的客户，继续处理年检、续保、维修和后续维护安排。',
    faqKicker: 'SERVICE FAQ',
    faqTitle: '常见问题',
    faqSubtitle: '先把客户最常问的几个节点说清楚，能明显减少二次确认和无效沟通。',
    faq1Question: '预约咨询后多久会收到回复？',
    faq1Answer: '通常会在 1-2 个工作日内由顾问联系；如果涉及在库确认或维修排期，会先说明当前能确认到哪一步。',
    faq2Question: '还没决定买哪台车，也可以先咨询吗？',
    faq2Answer: '可以。建议先说明预算、用途和偏好品牌，我们会先做购前评估，再决定是否进入保险、资料或交付准备。',
    faq3Question: '交车后的维修和年检还可以继续跟进吗？',
    faq3Answer: '可以，持有阶段仍可继续安排年检、续保、基础维修与保养建议，但具体时间与费用会按车辆状态单独确认。'
  },
  ja: {
    heroEyebrow: 'TK168 MOTOR GALLERY',
    heroTitle: '付加サービス',
    heroSubtitle: '中古車の取引、納車、保有フェーズに合わせて、店頭での実務支援を一つの導線にまとめています。',
    overviewKicker: 'VALUE-ADDED SERVICES',
    overviewTitle: '購入前判断、納車調整、保有後対応を一つの流れにまとめる',
    overviewSubtitle: '実際の中古車業務では、抽象的なサービス名よりも、誰が追うか、いつ返答するか、何をまとめて進められるかが重要です。',
    overviewText1: '成約後に時間がかかりやすいのは、見積判断、書類確認、保険相談、納車前点検、保有後の維持管理です。',
    overviewText2: 'TK168 ではこれらを一つの窓口に寄せ、車の状態とお客様の用途に応じて、先に何を進めるべきかを整理します。',
    overviewText3: 'そのためページ全体も「何でもできます」ではなく、「どこを任せると手間が減るか」が伝わる内容にしています。',
    overviewPrimary: '相談を予約する',
    overviewSecondary: '企業紹介を見る',
    metric1Label: '初回返答',
    metric1Value: '1-2 営業日',
    metric2Label: '対応言語',
    metric2Value: '中 / 日 / 英',
    metric3Label: '対応方法',
    metric3Value: '来店予約 / リモート相談',
    metric4Label: '主な対象',
    metric4Value: '在庫成約客と相談客',
    metric5Label: '実務上のすすめ方',
    metric5Value: '車両と納車時期を先に固めてから支援内容を決める',
    metric5Desc: '実際の成約フローに近く、途中で書類や予定を何度も直す状態を減らせます。',
    metricTag1: '査定',
    metricTag2: '手続き',
    metricTag3: '整備',
    flowKicker: 'MAINTENANCE FLOW',
    flowTitle: '整備とメンテナンスはどのように進むか',
    flowSubtitle: '予約、点検、見積、作業、引き渡しを順に見せることで、実際の流れが分かりやすくなります。',
    flowStep1Label: '01',
    flowStep1Title: '予約と症状確認',
    flowStep1Text: '異音、警告灯、定期点検の時期、外装修理の有無などを先に確認し、来店点検が必要かを判断します。',
    flowStep2Label: '02',
    flowStep2Title: '入庫点検と見積説明',
    flowStep2Text: '実車確認のうえで必要な作業項目、所要時間、費用感を整理して説明します。',
    flowStep3Label: '03',
    flowStep3Title: '整備・メンテナンス実施',
    flowStep3Text: '内容確定後に点検整備、消耗品交換、小規模修理を進め、同じ窓口で状況共有を続けます。',
    flowStep4Label: '04',
    flowStep4Title: '完了引き渡しと次回案内',
    flowStep4Text: '今回の作業内容、今後の注意点、次回メンテナンス時期を伝え、保有後対応につなげます。',
    matrixKicker: 'SERVICE MATRIX',
    matrixTitle: '成約前後によく相談される六つのサービス',
    matrixSubtitle: '予算確認、保険説明、書類連携、納車前点検などは、整備相談より先に検討されることが多い内容です。',
    module1Title: '購入前評価',
    module1Text: '年式、走行距離、装備、状態を踏まえ、この車を本当に進めるべきかを判断します。',
    module2Title: '保険説明と補助',
    module2Text: '用途と予算に応じて、いつ何を決めるべきかをわかりやすく整理します。',
    module3Title: '書類と手続きの連携',
    module3Text: '成約前後で止まりやすい書類確認、日程共有、各種手続きを同じ窓口で整理します。',
    module4Title: '納車前点検',
    module4Text: '気になる状態を納車前に説明し、引き渡し時の不安を減らします。',
    module5Title: '納車整備と修理',
    module5Text: '納車前の基本整備と、納車後に発生した小さな不具合への対応方針を整理します。',
    module6Title: '車検、更新、保有後メンテナンス',
    module6Text: '保有段階で必要な継続対応を支え、安定した利用状態を保てるようにします。',
    sceneKicker: 'COMMON COMBINATIONS',
    sceneTitle: 'よくある三つの相談場面',
    sceneSubtitle: '抽象的なパッケージではなく、実際の店頭相談に近い形で整理しています。',
    scene1Title: 'まだ車を比較中',
    scene1Text: '車種や予算を比較している段階で、購入前評価と基本的な手続き説明を受けたい方向けです。',
    scene2Title: '成約が決まった後',
    scene2Text: '資料、点検、保険、納車前整備をまとめて確認したい方向けです。',
    scene3Title: '納車後の維持管理',
    scene3Text: '車検、更新、修理、保有後のメンテナンス相談を継続したい方向けです。',
    faqKicker: 'SERVICE FAQ',
    faqTitle: 'よくある質問',
    faqSubtitle: '来店前によく確認される点を先にまとめ、無駄な往復確認を減らせる構成にしています。',
    faq1Question: '相談予約のあと、どれくらいで返答がありますか？',
    faq1Answer: '通常は 1-2 営業日以内に担当アドバイザーからご連絡します。在庫確認や整備枠の確認が必要な場合は、先に確認可能な範囲をお伝えします。',
    faq2Question: 'まだ購入車両を決めていなくても相談できますか？',
    faq2Answer: '可能です。ご予算、用途、希望ブランドを共有いただければ、先に購入前評価を行い、その後に保険や書類、納車準備へ進むべきかを整理します。',
    faq3Question: '納車後の修理や車検も継続して相談できますか？',
    faq3Answer: '可能です。保有フェーズに入った後も、車検、更新、軽整備、保養の相談を継続できますが、具体的な日程と費用は車両状態に応じて個別確認となります。'
  },
  en: {
    heroEyebrow: 'TK168 MOTOR GALLERY',
    heroTitle: 'Value-added Services',
    heroSubtitle: 'Practical offline support around used-car transactions, delivery, and ownership.',
    overviewKicker: 'VALUE-ADDED SERVICES',
    overviewTitle: 'Keeping pre-purchase judgment, delivery coordination, and aftercare on one service line',
    overviewSubtitle: 'In real used-car business, customers care less about abstract service names and more about who follows up, when they hear back, and what can be handled together.',
    overviewText1: 'After choosing a car, the time-consuming parts are often valuation, document checks, insurance discussions, pre-delivery inspection, and maintenance planning.',
    overviewText2: 'TK168 is best used as one window that organizes those scattered tasks and helps decide what should be handled first based on the vehicle and the customer’s use case.',
    overviewText3: 'So the page is not trying to say “we do everything”, but rather “these are the areas where we can reduce detours”.',
    overviewPrimary: 'Book a consultation',
    overviewSecondary: 'View company profile',
    metric1Label: 'First reply',
    metric1Value: '1-2 business days',
    metric2Label: 'Languages',
    metric2Value: 'CN / JP / EN',
    metric3Label: 'Format',
    metric3Value: 'Store visit / remote support',
    metric4Label: 'Best for',
    metric4Value: 'Stock buyers and inquiry clients',
    metric5Label: 'Practical advice',
    metric5Value: 'Confirm vehicle and delivery timing first, then choose the service mix',
    metric5Desc: 'This better matches real deal flow and reduces repeated document or schedule changes later.',
    metricTag1: 'Appraisal',
    metricTag2: 'Paperwork',
    metricTag3: 'Maintenance',
    flowKicker: 'MAINTENANCE FLOW',
    flowTitle: 'How maintenance support usually moves forward',
    flowSubtitle: 'Breaking down booking, inspection, quotation, work, and handover gives customers a clearer expectation than simply saying “maintenance is available.”',
    flowStep1Label: '01',
    flowStep1Title: 'Booking and issue check',
    flowStep1Text: 'We first confirm noise, warning lights, service cycle, or damage position to decide whether an in-person inspection is needed.',
    flowStep2Label: '02',
    flowStep2Title: 'Inspection and quotation',
    flowStep2Text: 'After checking the vehicle, we explain the recommended work, timing, and expected price range.',
    flowStep3Label: '03',
    flowStep3Title: 'Maintenance work',
    flowStep3Text: 'Once confirmed, we arrange service, consumable replacement, or light repairs, with one advisor staying on the progress.',
    flowStep4Label: '04',
    flowStep4Title: 'Delivery and next reminder',
    flowStep4Text: 'After completion, we explain what was done, what to watch next, and when the next visit should happen.',
    matrixKicker: 'SERVICE MATRIX',
    matrixTitle: 'Six service topics customers ask about most often',
    matrixSubtitle: 'Budget checks, insurance guidance, documents, and pre-delivery inspection often come into the decision flow earlier than maintenance itself.',
    module1Title: 'Pre-purchase evaluation',
    module1Text: 'Looking at year, mileage, specification, and condition to decide whether the vehicle is worth pursuing.',
    module2Title: 'Insurance support',
    module2Text: 'Explaining the basics based on budget and usage so the customer knows what to prepare and when to confirm.',
    module3Title: 'Document coordination',
    module3Text: 'Keeping the documents, reminders, and paperwork that often slow a deal under one window.',
    module4Title: 'Pre-delivery inspection',
    module4Text: 'Making the condition checks customers care about visible before delivery so the handover feels clearer.',
    module5Title: 'Delivery preparation and repair',
    module5Text: 'Suitable for basic work before handover and smaller repair advice after delivery.',
    module6Title: 'Inspection, renewal, and aftercare',
    module6Text: 'Continuing to support inspection, renewal planning, and later maintenance during ownership.',
    sceneKicker: 'COMMON COMBINATIONS',
    sceneTitle: 'Three common consultation situations',
    sceneSubtitle: 'Instead of abstract packages, this section is organized around the kinds of conversations that happen in the store.',
    scene1Title: 'Still comparing vehicles',
    scene1Text: 'For customers still comparing models and budgets, starting with appraisal and then basic documents or insurance guidance.',
    scene2Title: 'Deal already decided',
    scene2Text: 'For customers who already chose the vehicle and want documents, checks, insurance, and delivery prep handled together.',
    scene3Title: 'Already in ownership',
    scene3Text: 'For customers who already took delivery and need inspection, renewal, repair, or ongoing maintenance support.',
    faqKicker: 'SERVICE FAQ',
    faqTitle: 'Frequently asked questions',
    faqSubtitle: 'Clarifying the most common questions in advance reduces repeated confirmation later.',
    faq1Question: 'How quickly do I hear back after booking?',
    faq1Answer: 'Usually within 1-2 business days. If stock confirmation or maintenance scheduling is involved, we first explain what can already be confirmed.',
    faq2Question: 'Can I ask even before choosing a vehicle?',
    faq2Answer: 'Yes. Share your budget, use case, and preferred brands first, and we can start with pre-purchase evaluation before deciding whether to move into insurance, document, or delivery preparation.',
    faq3Question: 'Can support continue after delivery for repair or inspection?',
    faq3Answer: 'Yes. Inspection, renewal, light repairs, and maintenance advice can still be arranged after delivery, with timing and cost confirmed separately based on vehicle condition.'
  }
};

function applyServiceCopy(language = 'ja') {
  const catalog = SERVICE_COPY[language] || SERVICE_COPY.ja || SERVICE_COPY.zh;
  document.title = `${catalog.heroTitle} — TK168 Premium Automotive`;
  document.querySelectorAll('[data-service-key]').forEach((element) => {
    const key = element.dataset.serviceKey || '';
    if (catalog[key]) element.textContent = catalog[key];
  });
}

window.TK168CommonLinks?.applyCommonLinks();
window.TK168PageChrome?.applyPageChrome({
  pageKey: 'service',
  inventoryHref: 'brand.html',
  serviceHref: 'service.html'
});

applyServiceCopy(window.TK168I18N?.getLanguage?.() || 'ja');

window.addEventListener('tk168:languagechange', (event) => {
  applyServiceCopy(event.detail?.language || 'ja');
});
