#!/usr/bin/env node
// Generates schema/seed.sql by loading the existing js/data.js
// baseVehicles array + condition/listing/highlight presets, so the new
// D1 database starts with the same 13 vehicles already shown on the site.

import { readFileSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const dataPath = resolve(__dirname, "../../js/data.js");
const raw = readFileSync(dataPath, "utf8");

function sliceArrayLiteral(source, name) {
  const marker = `const ${name} = [`;
  const start = source.indexOf(marker);
  if (start === -1) throw new Error(`Cannot find ${name} in data.js`);
  const arrStart = start + marker.length - 1; // points at '['
  let depth = 0;
  for (let i = arrStart; i < source.length; i++) {
    const ch = source[i];
    if (ch === "[") depth++;
    else if (ch === "]") {
      depth--;
      if (depth === 0) return source.slice(arrStart, i + 1);
    }
  }
  throw new Error(`Unterminated ${name}`);
}

function sliceObjectLiteral(source, name) {
  const marker = `const ${name} = {`;
  const start = source.indexOf(marker);
  if (start === -1) throw new Error(`Cannot find ${name} in data.js`);
  const objStart = start + marker.length - 1;
  let depth = 0;
  for (let i = objStart; i < source.length; i++) {
    const ch = source[i];
    if (ch === "{") depth++;
    else if (ch === "}") {
      depth--;
      if (depth === 0) return source.slice(objStart, i + 1);
    }
  }
  throw new Error(`Unterminated ${name}`);
}

// Evaluate the literals in a sandbox-like way.  data.js references
// defaultBenefits/defaultFeatures, so inject them.
const defaultBenefits = [
  "一年质保服务",
  "支持旧车置换",
  "可选金融分期",
  "专属交付顾问",
];
const defaultFeatures = [
  "质检认证",
  "现车在库",
  "全国配送",
  "手续透明",
  "专人跟进",
  "售后支持",
  "急速交付",
];

const baseVehiclesSrc = sliceArrayLiteral(raw, "baseVehicles");
const conditionSrc = sliceObjectLiteral(raw, "vehicleConditionPresets");
const listingSrc = sliceObjectLiteral(raw, "vehicleListingPresets");
const highlightSrc = sliceObjectLiteral(raw, "vehicleHighlightPresets");

const baseVehicles = new Function(
  "defaultBenefits",
  "defaultFeatures",
  `return ${baseVehiclesSrc};`
)(defaultBenefits, defaultFeatures);
const vehicleConditionPresets = new Function(`return ${conditionSrc};`)();
const vehicleListingPresets = new Function(`return ${listingSrc};`)();
const vehicleHighlightPresets = new Function(`return ${highlightSrc};`)();

function esc(value) {
  if (value === null || value === undefined) return "NULL";
  const s = String(value).replace(/'/g, "''");
  return `'${s}'`;
}

function escJson(value) {
  if (value === null || value === undefined) return "NULL";
  return esc(JSON.stringify(value));
}

function presetJson(preset) {
  return preset ? escJson(preset) : "NULL";
}

const lines = [];
lines.push("-- Generated by worker/schema/build-seed.mjs. Do not edit by hand.");
lines.push("-- Re-run `node worker/schema/build-seed.mjs` after editing js/data.js.");
lines.push("DELETE FROM vehicle_images;");
lines.push("DELETE FROM vehicles;");

baseVehicles.forEach((v, index) => {
  const cond = vehicleConditionPresets[v.id] || {};
  const listing = vehicleListingPresets[v.id] || {};
  const highlight = vehicleHighlightPresets[v.id] || {};

  const insert = `INSERT INTO vehicles (
    id, brand_key, name, year, type, icon, mileage, engine, fuel, trans,
    total_price, base_price, body_style, drive, body_color, interior_color,
    seats, service_record, origin,
    overview_zh, overview_ja, overview_en, benefits, features,
    cond_non_smoking, cond_authorized_import, cond_dealer_warranty,
    cond_eco_tax_eligible, cond_one_owner, cond_rental_up,
    listing_repair_history, listing_vehicle_inspection, listing_legal_maintenance, listing_periodic_book,
    highlight_steering, highlight_chassis_tail,
    display_order, is_published
  ) VALUES (
    ${esc(v.id)}, ${esc(v.brandKey)}, ${esc(v.name)}, ${esc(v.year)}, ${esc(v.type)},
    ${esc(v.icon)}, ${esc(v.mileage)}, ${esc(v.engine)}, ${esc(v.fuel)}, ${esc(v.trans)},
    ${esc(v.totalPrice)}, ${esc(v.basePrice)}, ${esc(v.bodyStyle)}, ${esc(v.drive)},
    ${esc(v.bodyColor)}, ${esc(v.interiorColor)}, ${esc(v.seats)}, ${esc(v.serviceRecord)}, ${esc(v.origin)},
    ${escJson(v.overview)}, ${escJson(v.overviewJa)}, ${escJson(v.overviewEn || null)},
    ${escJson(v.benefits)}, ${escJson(v.features)},
    ${presetJson(cond.nonSmoking)}, ${presetJson(cond.authorizedImport)}, ${presetJson(cond.dealerWarranty)},
    ${presetJson(cond.ecoTaxEligible)}, ${presetJson(cond.oneOwner)}, ${presetJson(cond.rentalUp)},
    ${presetJson(listing.repairHistory)}, ${presetJson(listing.vehicleInspection)},
    ${presetJson(listing.legalMaintenance)}, ${presetJson(listing.periodicInspectionBook)},
    ${presetJson(highlight.steering)}, ${presetJson(highlight.chassisTail)},
    ${index}, 1
  );`;
  lines.push(insert);

  (v.gallery || [v.photo]).forEach((img, i) => {
    // Seed images reference the existing assets/images/<file>.  We store
    // them as relative URLs so the frontend keeps working immediately.
    const url = img.startsWith("assets/") || /^https?:/.test(img)
      ? img
      : `assets/images/${img}`;
    lines.push(
      `INSERT INTO vehicle_images (vehicle_id, r2_key, url, alt, is_primary, position) VALUES (${esc(
        v.id
      )}, ${esc("seed:" + v.id + ":" + i)}, ${esc(url)}, ${esc(v.name)}, ${i === 0 ? 1 : 0}, ${i});`
    );
  });
});

const out = resolve(__dirname, "seed.sql");
writeFileSync(out, lines.join("\n") + "\n", "utf8");
console.log(`Wrote ${out} with ${baseVehicles.length} vehicles.`);
